### PR TITLE
Add glob change to support npm private modules

### PR DESCRIPTION
**Pull request by jefflembeck**
npm's scoped modules allow one to scope to a specific namespace, org or personal.

An example of this would be `@npmcorp/pui-css-typography` instead of the main `pui-css-typography`

Shout out to @rockbot for this solution

Needed: tests, but I don't know how this test framework/setup works yet

### CODE REVIEW

**Comment by aredridel** [comment]
NICE

**Comment by aredridel** [comment]
Test case?

**Comment by jefflembeck** [comment]
@aredridel working on that part - trying to learn how the tests work

**Comment by stubbornella** [comment]
<3

**Pull request merged**
